// <auto-generated/>
#pragma warning disable CS0618
using ConfigureService.Client.Api.AccountType.GetAccountTypeList;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ConfigureService.Client.Api.AccountType
{
    /// <summary>
    /// Builds and executes requests for operations under \api\AccountType
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class AccountTypeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GetAccountTypeList property</summary>
        public global::ConfigureService.Client.Api.AccountType.GetAccountTypeList.GetAccountTypeListRequestBuilder GetAccountTypeList
        {
            get => new global::ConfigureService.Client.Api.AccountType.GetAccountTypeList.GetAccountTypeListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ConfigureService.Client.Api.AccountType.AccountTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountTypeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/AccountType", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ConfigureService.Client.Api.AccountType.AccountTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountTypeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/AccountType", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
