// <auto-generated/>
#pragma warning disable CS0618
using FinancialService.Client.AccountBalance.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace FinancialService.Client.AccountBalance
{
    /// <summary>
    /// Builds and executes requests for operations under \AccountBalance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class AccountBalanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the FinancialService.Client.AccountBalance.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder"/></returns>
        public global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the FinancialService.Client.AccountBalance.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("userId", position);
                return new global::FinancialService.Client.AccountBalance.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FinancialService.Client.AccountBalance.AccountBalanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountBalanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/AccountBalance", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::FinancialService.Client.AccountBalance.AccountBalanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountBalanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/AccountBalance", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
