name: Build and Push Docker Image to ECR

on:
  workflow_run:
    workflows: ["Code Scan"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      
      - name: Get version code
        id: get-version-code
        run: echo "::set-output name=version-code::$(cat VERSION.txt)"

      - name: Build, tag, and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: poc-dev/userservice
          COMMIT_HASH: ${{ steps.get-commit-hash.outputs.commit-hash }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          VERSION_CODE: ${{ steps.get-version-code.outputs.version-code }}
        run: |
          IMAGE_TAG=${VERSION_CODE}-${COMMIT_HASH}-${GITHUB_RUN_NUMBER}
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG